### ISSUE TITLE
多人脸图片检测不全问题

### ISSUE THREAD

**Issue by wyh163** [DeepVAC/libdeepvac#25]
目前对30人脸以下的图片检测效果较好    
检测多人脸的图片是效果不好，比较容易出现漏检现象    
主要原因参考变量：
[top_k](https://github.com/DeepVAC/libdeepvac/blob/8bb6f45e739adfc77645ffee5f2ec1c1922f37d5/modules/src/syszux_face_retina.cpp#L79)
[keep_top_k](https://github.com/DeepVAC/libdeepvac/blob/8bb6f45e739adfc77645ffee5f2ec1c1922f37d5/modules/src/syszux_face_retina.cpp#L94)
若要识别100左右的人脸，可适当增大这两个变量的值（参考值：150）

**Comment by gemfield** [comment]
已经增加了set API， 即将关闭这个问题。
