### ISSUE TITLE
consulting about libtorch memory leak

### ISSUE THREAD

**Issue by aluminumbox** [DeepVAC/libdeepvac#35]
Hi, I am using libtorch-cxx11-abi-shared-with-deps-1.6.0+cpu.zip, which is downloaded from Pytorch official website. Howere, I have experience memory leak during inference. I use valgrind and checked, the leak happened in location below:

```
==107045== 69,664 bytes in 1 blocks are possibly lost in loss record 87,916 of 88,026
==107045==    at 0x483C855: malloc (vg_replace_malloc.c:380)
==107045==    by 0x95D7857: mm_account_ptr_by_tid..0 (in /opt/e2e-streamingASR/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so)
==107045==    by 0x95D6CB1: mkl_serv_malloc (in /opt/e2e-streamingASR/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so)
==107045==    by 0x8B9E3F6: mkl_serv_domain_get_max_threads (in /opt/e2e-streamingASR/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so)
==107045==    by 0x531C8B8: at::init_num_threads() (in /opt/e2e-streamingASR/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so)
==107045==    by 0x5D26184: THFloatTensor_equalImpl(c10::TensorImpl*, c10::TensorImpl*) [clone .constprop.349] (in /opt/e2e-streamingASR/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so)
==107045==    by 0x5D26336: THFloatTensor_equal(c10::TensorImpl*, c10::TensorImpl*) (in /opt/e2e-streamingASR/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so)
==107045==    by 0x5BBCE31: at::native::legacy::cpu::_th_equal(at::Tensor const&, at::Tensor const&) (in /opt/e2e-streamingASR/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so)
==107045==    by 0x771B27D: torch::autograd::VariableType::equal(at::Tensor const&, at::Tensor const&) (in /opt/e2e-streamingASR/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so)
==107045==    by 0x7D826CD: torch::jit::(anonymous namespace)::tensorEqual(at::Tensor const&, at::Tensor const&) (in /opt/e2e-streamingASR/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so)
==107045==    by 0x7D85134: torch::jit::(anonymous namespace)::attributesEqualCSE(torch::jit::Node const*, torch::jit::Node const*) [clone .constprop.364] (in /opt/e2e-streamingASR/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so)
==107045==    by 0x7D85D97: torch::jit::EqualNode::operator()(torch::jit::Node const*, torch::jit::Node const*) const (in /opt/e2e-streamingASR/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so)
```

I wonder have you experience similar problem when using libtorch? If so, could you please give me some insight how to solve it?

**Comment by gemfield** [comment]
Please be noted that memory Increase != memory leak, instead, you can report below RSS info here:
1, the libtorch process RSS usage after 100 times inference (i.e. the memory usage is stable now);
2,  the libtorch process RSS usage after 200 times inference;
If memory usage increase dramatically during 100 and 200 times inference, then you can test your code on MLab HomePod 2.0 pro. If memory still leak on HomePod environment, we can help to debug this issue.

**Comment by liankid** [comment]
> Please be noted that memory Increase != memory leak, instead, you can report below RSS info here:
> 1, the libtorch process RSS usage after 100 times inference (i.e. the memory usage is stable now);
> 2, the libtorch process RSS usage after 200 times inference;
> If memory usage increase dramatically during 100 and 200 times inference, then you can test your code on MLab HomePod 2.0 pro. If memory still leak on HomePod environment, we can help to debug this issue.

Thank you for your reply. Yes though valgrind shows possible lost, but the RSS is relatively stable, increase a little but not dramatically after some inference. So, I think maybe there is no problem at all.

**Comment by aluminumbox** [comment]
> Please be noted that memory Increase != memory leak, instead, you can report below RSS info here:
> 1, the libtorch process RSS usage after 100 times inference (i.e. the memory usage is stable now);
> 2, the libtorch process RSS usage after 200 times inference;
> If memory usage increase dramatically during 100 and 200 times inference, then you can test your code on MLab HomePod 2.0 pro. If memory still leak on HomePod environment, we can help to debug this issue.

Thank you for your reply. Yes though valgrind shows possible lost, but the RSS is relatively stable, increase a little but not dramatically after some inference. So, I think maybe there is no problem at all.

**Comment by gemfield** [comment]
不客气。
